// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsWz00N33vUeUHbQQ0HcG6-bfbpojqYX8',
    appId: '1:446760353106:web:8b0174bca8027afba58e8b',
    messagingSenderId: '446760353106',
    projectId: 'atherio-c2262',
    authDomain: 'atherio-c2262.firebaseapp.com',
    storageBucket: 'atherio-c2262.firebasestorage.app',
    measurementId: 'G-9JRK4JHRFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpSAnY3A2stMjWWB9Kx5zh_iyA7oJrvjQ',
    appId: '1:446760353106:android:486325cca5c9d991a58e8b',
    messagingSenderId: '446760353106',
    projectId: 'atherio-c2262',
    storageBucket: 'atherio-c2262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODUkYgCSEdSpGFJE33R-dzIu6ujUUf1g',
    appId: '1:446760353106:ios:3a154ffb69b5dd87a58e8b',
    messagingSenderId: '446760353106',
    projectId: 'atherio-c2262',
    storageBucket: 'atherio-c2262.firebasestorage.app',
    iosBundleId: 'com.atherioappiddirsavage.atherio',
  );
}
